# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 051929fe564ac2c6c92f5cab7aaf8a74e8977734397fb0df3314dae491f5fefd9a1c46b6250dbf9a6fa08049d2056c2db524e3b91caf7e6255915c79f7b24f21

test:
  secret_key_base: ea8d0cac379d61284383e4a76c958d5ffa1c30cc4c1420f75c8d8b11b98a0d6da0cebb9243b7daf567ae506f43491afec86264f44459f33221fa25f0131c92e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
